name: Deploy Quartz site

on:
  push:
    branches:
      - main
  workflow_dispatch:  # allows manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout Obsidian Vault (this repo)
      - name: Checkout Obsidian Vault
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Checkout Quartz Repo (private fork)
      - name: Checkout Quartz Repo
        uses: actions/checkout@v4
        with:
          repository: Random-Coder-Dude/Quartz
          path: quartz
          token: ${{ secrets.QUIRZ_PAT }}   # Personal Access Token for private repo
          fetch-depth: 0

      # 3. Sync Obsidian vault into Quartz content folder
      - name: Sync Obsidian Vault into Quartz Content
        run: |
          rm -rf quartz/content
          mkdir -p quartz/content
          rsync -av --exclude='quartz' --exclude='.github' --exclude='.git' ./ quartz/content/

      # 4. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # 5. Install Quartz dependencies
      - name: Install Dependencies
        working-directory: quartz
        run: npm install

      # 6. Build Quartz site
      - name: Build Quartz Site
        working-directory: quartz
        run: npx quartz build

      # 7. Upload artifact for Pages
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: quartz/public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
